name: Build & Deploy


on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username:  ${{secrets.SSH_USERNAME}}
          key: ${{secrets.DEPLOY_KEY}}


          script: |
            mkdir test
            cd test
            git clone https://github.com/agiledev-students-fall2022/final-project-team-stranger.git
            echo "Deploy Successful"